# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [4]:
# 記得先 Import 正確的套件

import numpy as np
x = np.arange(1,12)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [51]:
mask = np.logical_and(x>2, x<7)

x[mask] * -1

array([-3, -4, -5, -6])

In [52]:
for i in x:
    if mask[i-1] == 1:
        print(x[i-1]*-1)
    else:
        print(x[i-1])
    

1
2
-3
-4
-5
-6
7
8
9
10
11


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [24]:
A = np.random.rand(3, 6)

print(A)

[[0.49794617 0.6065969  0.82530767 0.21841703 0.49910817 0.55488826]
 [0.1621154  0.89435675 0.20129678 0.91678457 0.48551077 0.32850142]
 [0.86286021 0.3514328  0.19555835 0.65503348 0.85567021 0.25664383]]


In [29]:
len(A[A>0.5])

8

In [30]:
A[A>0.5]

array([0.6065969 , 0.82530767, 0.55488826, 0.89435675, 0.91678457,
       0.86286021, 0.65503348, 0.85567021])